// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'sortable.freezed.dart';

@freezed
sealed class Sortable with _$Sortable {
  const Sortable._();

  const factory Sortable.int(PlatformInt64 field0) = Sortable_Int;
  const factory Sortable.float(double field0) = Sortable_Float;
  const factory Sortable.bool(bool field0) = Sortable_Bool;
  const factory Sortable.strIdx(int field0) = Sortable_StrIdx;
  const factory Sortable.null_() = Sortable_Null;
}
