// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/sortable.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint32List> sortByPriority({
  required List<Sortable> data,
  required List<int> ids,
  required BigInt width,
  required Uint64List priorities,
  required List<bool> directions,
  required List<String> stringsPool,
}) => RustLib.instance.api.crateApiSortSortByPriority(
  data: data,
  ids: ids,
  width: width,
  priorities: priorities,
  directions: directions,
  stringsPool: stringsPool,
);
